### ISSUE TITLE
[INFRA] Create a first release

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-pm4py#11]
We should tag and create a GitHub release for this demo.
This lets easily track the changes and clearly bookmark the code.

I suggest we tag the first version as `v1.0.0` to state this is not an experimental demo.

```[tasklist]
### Tasks
- [x] document the release process #17
- [x] if possible automate task. Only create a tag, this will be done by creating GitHub releases
- [x] create the first tag/version: https://github.com/process-analytics/bpmn-visualization-pm4py/releases/tag/v1.0.0
```
