### ISSUE TITLE
[FEAT] Add statistics on edges

### ISSUE THREAD

**Issue by assynour** [process-analytics/bpmn-visualization-pm4py#33]
Prior to pm4py 2.6.1, it was not possible to get the statistics related to edges from the Petri net corresponding to the BPMN. 

The fix has been introduced in 2.6.1: https://github.com/pm4py/pm4py-core/commit/84e85c6e4715fe58159f6cfb83248d1cfa28bc8e

Update the code to take into account this fix.

```[tasklist]
### Tasks
- [ ] Update `compute_frequency` function in the backend
- [ ] Update `discovery.js` file in the frontend to take into account the changes introduced in the backend
- [ ] Update `discovery.js` file in the frontend to add the statistics on the edges and update their styles accordingly
```
